### ISSUE TITLE
AMRITA: an online database for herbal medicine

### ISSUE THREAD

**Issue by anayan321** [open-life-science/ols-1#19]
Project Lead:
@anayan321
@davidviryachen

Mentor: @hdinkel

Welcome to OLS-1! This issue will be used to track your project and progress during the program. Please use this checklist over the next few weeks as you start Open Life Science program :tada:.

***

Before Week 1 (Jan 20): Meet your mentor!
- [x] Create an account on [GitHub](https://github.com)
- [x] Complete **your own copy** of the [open leadership self-assessment](https://docs.google.com/document/d/1oQgdfj4lPnypAyb9_Ba0Zt7E8J5L6qMvuKwu0wgQsjs/edit?usp=sharing) and share it to your mentor
  
  If you're a group, each teammate should complete this assessment individually. This is here to help you set your own personal goals during the program. No need to share your results, but be ready to share your thoughts with your mentor.

- [x] Make sure you know when and how you'll be meeting with your mentor.

Before Week 2 (Jan 27): Cohort Call (Welcome to Open Life Science!)
- [x] Create an issue on the [OLS-1 GitHub repository](https://github.com/open-life-science/ols-1/issues/new) for your OLS work and share the link to your mentor.
- [x] Draft a brief vision statement using your goals

  [This lesson](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/) from the Open Leadership Training Series (OLTS) might be helpful

- [x] Leave a comment on this issue with your draft vision statement & be ready to share this on the call
- [x] Check the [Syllabus](https://openlifesci.org/ols-1) for notes and connection info for all the cohort calls.

Before Week 3 (Feb 3): Meet your mentor!
- [x] Look up two other projects and comment on their issues with feedback on their vision statement
- [x] Complete this [compare and contrast assignment](https://docs.google.com/document/d/1ukvqDRIYfvCapVMdE5hWP-0MkLNJ9T65X43O7F336Ac/edit?usp=sharing) about current and desired community interactions and value exchanges
- [x] Complete your Open Canvas ([instructions](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/), [canvas](https://docs.google.com/presentation/d/1MeJo0TyuMg_waLk1J4q9y1aAqKNMuRBlnmxEChSz-cQ/edit?usp=sharing))
- [x] Share a link to your Open Canvas in your GitHub issue
- [x] Start your [Roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/)
- [ ] Comment on your issue with your draft Roadmap
- [x] Suggest a cohort name at the bottom of the shared notes and vote on your favorite with a +1

Before Week 4 (Feb 10): Cohort Call (Tooling and roadmapping for Open projects)
- [ ] Look up two other projects and comment on their issues with feedback on their open canvas.

Week 5 and more
- [x] Create a GitHub repository for your project
- [ ] Add the link to your repository in your issue
- [ ] Use your canvas to [start writing a `README.md` file](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/), or landing page, for your project
- [x] Link to your README in a comment on this issue
- [x] Add an [open license](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/sharing-your-work-in-the-open/) to your repository as a file called `LICENSE.md`
- [ ] Add a [Code of Conduct](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-a-code-of-conduct/) to your repository as a file called `CODE_OF_CONDUCT.md`
- [ ] Invite new contributors to into your work!

This issue is here to help you keep track of work as you start Open Life Science program. Please refer to the [OLS-1 Syllabus](https://openlifesci.org/ols-1) for more detailed weekly notes and assignments past week 4.

### Vision statement
We hope to work with scientists from various disciplines to construct an online database for herbal medicine so that research community and private sectors could work in collaboration to advance the field.

As initial project, we will combine the herbal medicine database from Thailand and Indonesia.

### Open Canvas
The link to our Open Canvas is below:
https://docs.google.com/presentation/d/1vXj03t_X6GDjGGrW29NVFBtpp-8pnhPYcr44uOKxrK8/edit#slide=id.p

## Roadmap
The link to our Roadmap is below:
https://docs.google.com/document/d/1SjqB6HPOekwD5dWiwehMGUQyW4DefLhxe9HoLAbDw7o/edit

**Comment by anayan321** [comment]
Upgoer5 Vision statement:

Our team hope to work with people from many fields to build a place to keep the studies about ways to make sick people well with things we can find in the wood such as leaves, or other parts of trees. People can get into this place by their computers or phones so they can work together although they are far away and all of us could move this field faster.

**Comment by bruno-soares** [comment]
Hi! I really enjoyed your project. I've been studying a bit of ethnobotany in the past years and it is so difficult to review information as scientists from different areas usually do not interact so well (at least here in Brazil).

**Comment by anayan321** [comment]
> Hi! I really enjoyed your project. I've been studying a bit of ethnobotany in the past years and it is so difficult to review information as scientists from different areas usually do not interact so well (at least here in Brazil).

Hi, thank you for your comment. We didn't think about ethnobotany before but it could be very interesting aspect to be included in our work :)

**Comment by malvikasharan** [comment]
Hi Project Leads,  

This is your project report file: https://hackmd.io/kHIlrV_FS62gN-bOclaHOg

Please start working on it for the final presentation. We will send more info in the weekly email.  
Best, 
OLS team
