### ISSUE TITLE
Creating a network of Data Champions (VU Amsterdam)

### ISSUE THREAD

**Issue by Karvovskaya** [open-life-science/ols-1#6]
Welcome to OLS-1! This issue will be used to track your project and progress during the program. Please use this checklist over the next few weeks as you start Open Life Science program :tada:.

***
Before Week 1 (Jan 20): Meet your mentor!
- [x] Create an account on GitHub
- [x] Complete your own copy of the open leadership self-assessment and share it to your mentor
If you're a group, each teammate should complete this assessment individually. This is here to help you set your own personal goals during the program. No need to share your results, but be ready to share your thoughts with your mentor.
 - [x] Make sure you know when and how you'll be meeting with your mentor.

Before Week 2 (Jan 27): Cohort Call (Welcome to Open Life Science!)
- [x] Create an issue on the OLS-1 GitHub repository for your OLS work and share the link to your mentor.
- [x]  Draft a brief vision statement using your goals
This lesson from the Open Leadership Training Series (OLTS) might be helpful
- [x]  Leave a comment on this issue with your draft vision statement & be ready to share this on the call
- [x]  Check the Syllabus for notes and connection info for all the cohort calls.

Before Week 3 (Feb 3): Meet your mentor!
- [x] Look up two other projects and comment on their issues with feedback on their vision statement
- [ ] Complete this [compare and contrast assignment](https://docs.google.com/document/d/1ukvqDRIYfvCapVMdE5hWP-0MkLNJ9T65X43O7F336Ac/edit?usp=sharing) about current and desired community interactions and value exchanges
- [x] Complete your Open Canvas ([instructions](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/), [canvas](https://docs.google.com/presentation/d/1MeJo0TyuMg_waLk1J4q9y1aAqKNMuRBlnmxEChSz-cQ/edit?usp=sharing))
- [x] Share a link to your Open Canvas in your GitHub issue
- [x] Start your [Roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/)
- [x] Comment on your issue with your draft Roadmap
- [x] Suggest a cohort name at the bottom of the shared notes and vote on your favorite with a +1

Before Week 4 (Feb 10): Cohort Call (Tooling and roadmapping for Open projects)
- [ ] Look up two other projects and comment on their issues with feedback on their open canvas.

Week 5 and more
- [x] Create a GitHub repository for your project
- [ ] Add the link to your repository in your issue
- [ ] Use your canvas to [start writing a `README.md` file](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/), or landing page, for your project
- [ ] Link to your README in a comment on this issue
- [x] Add an [open license](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/sharing-your-work-in-the-open/) to your repository as a file called `LICENSE.md`
- [ ] Add a [Code of Conduct](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-a-code-of-conduct/) to your repository as a file called `CODE_OF_CONDUCT.md`
- [ ] Invite new contributors to into your work!

This issue is here to help you keep track of work as you start Open Life Science program. Please refer to the [OLS-1 Syllabus](https://openlifesci.org/ols-1) for more detailed weekly notes and assignments past week 4.

**Comment by Karvovskaya** [comment]
Project Lead: @Karvovskaya 
Mentor: @pherterich

**Comment by Karvovskaya** [comment]
# Vision statement
I hope to work with advocates of open science to set up a Data Champions program so that the researchers at VU Amsterdam can learn about good RDM practice and receive support in their work with digital data.

**Comment by bebatut** [comment]
@Karvovskaya feel free to edit the issue’s checklist above once you are done with a task

**Comment by Fnyasimi** [comment]
This is a really nice project and it will improve data sharing and re-usability within and outside the institution

**Comment by cassgvp** [comment]
Hey @Karvovskaya ! I'd be interested to hear your ideas around how your are going to develop, train and support your Data Champions, and how you are going to generate support for these roles / responsibilities in the University. I'm going to be doing something similar on #15 - We should work together! 😃

**Comment by Lilian9** [comment]
Quite interesting project and looking forward to learning how you will be developing RDM program while engaging open science advocates from the start. And, how this will shape its use both for open science advocates and newbies

**Comment by Karvovskaya** [comment]
> @Karvovskaya feel free to edit the issue’s checklist above once you are done with a task

I am afraid I messed up the text file  :(

**Comment by Karvovskaya** [comment]
> Hey @Karvovskaya ! I'd be interested to hear your ideas around how your are going to develop, train and support your Data Champions, and how you are going to generate support for these roles / responsibilities in the University. I'm going to be doing something similar on #15 - We should work together! 😃

Hey @cassgvp, I would love to talk about this more. I am new at this university (started my job three days ago), so there are tons of things I need to figure out!

**Comment by Karvovskaya** [comment]
@Lilian9 I really enjoyed talking to you during the cohort call. Thanks for your comments. I am also curious about how useful the project will be. The idea is that researchers eagerly ask each other for advice. So if you have people who are willing to volunteer their knowledge, you have better chances to get your message across.

**Comment by Karvovskaya** [comment]
Open Canvas for my project can be found here https://docs.google.com/presentation/d/106ZGW2e_myZqohYwT5Foz4_ujD_F91PeBt8KVBhKhUw/edit?usp=sharing

**Comment by Karvovskaya** [comment]
# Roadmap Sketch

## Short term
- [ ] Creating awareness about the initiative at the library, management team and the data stewards within faculties

## Medium term 
- [ ] Approaching researchers at the faculties
- [ ] Determining a reward system 
- [ ] Creating an inventory of the data management services offered by the library 

## Long term 
- [ ] Nominating  data champions
- [ ] Setting up regular meetings with the data champions
- [ ] Figuring out the next goals for the whole group

**Comment by yochannah** [comment]
Hi Project Leads,

  This is your project report file: 

https://hackmd.io/f6PH7XuZRLGyuB_XYV1rNw?both

Please start working on it for the final presentation. We will send more info in the weekly email.

  Best,  

OLS team
