### ISSUE TITLE
Open-Connect-Kenya

### ISSUE THREAD

**Issue by Lilian9** [open-life-science/ols-1#7]
Project Lead: @Lilian9
Mentor: @kipkurui

Welcome to OLS-1! This issue will be used to track your project and progress during the program. Please use this checklist over the next few weeks as you start Open Life Science program :tada:.

***

Before Week 1 (Jan 20): Meet your mentor!
- [x] Create an account on [GitHub](https://github.com)
- [x] Complete **your own copy** of the [open leadership self-assessment](https://docs.google.com/document/d/1oQgdfj4lPnypAyb9_Ba0Zt7E8J5L6qMvuKwu0wgQsjs/edit?usp=sharing) and share it to your mentor
  
  If you're a group, each teammate should complete this assessment individually. This is here to help you set your own personal goals during the program. No need to share your results, but be ready to share your thoughts with your mentor.

- [x] Make sure you know when and how you'll be meeting with your mentor.

Before Week 2 (Jan 27): Cohort Call (Welcome to Open Life Science!)
- [x] Create an issue on the [OLS-1 GitHub repository](https://github.com/open-life-science/ols-1/issues/new) for your OLS work and share the link to your mentor.
- [x] Draft a brief vision statement using your goals

  [This lesson](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/) from the Open Leadership Training Series (OLTS) might be helpful

- [x] Leave a comment on this issue with your draft vision statement & be ready to share this on the call
- [x] Check the [Syllabus](https://openlifesci.org/ols-1) for notes and connection info for all the cohort calls.

Before Week 3 (Feb 3): Meet your mentor!
- [x] Look up two other projects and comment on their issues with feedback on their vision statement
- [x] Complete this [compare and contrast assignment](https://docs.google.com/document/d/1ukvqDRIYfvCapVMdE5hWP-0MkLNJ9T65X43O7F336Ac/edit?usp=sharing) about current and desired community interactions and value exchanges
- [x] Complete your Open Canvas ([instructions](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/), [canvas](https://docs.google.com/presentation/d/1MeJo0TyuMg_waLk1J4q9y1aAqKNMuRBlnmxEChSz-cQ/edit?usp=sharing))
- [x] Share a link to your Open Canvas in your GitHub issue
- [x] Start your [Roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/)
- [x] Comment on your issue with your draft Roadmap
- [ ] Suggest a cohort name at the bottom of the shared notes and vote on your favorite with a +1

Before Week 4 (Feb 10): Cohort Call (Tooling and roadmapping for Open projects)
- [x] Look up two other projects and comment on their issues with feedback on their open canvas.

Week 5 and more
- [x] Create a GitHub repository for your project
- [x] Add the link to your repository in your issue
- [x] Use your canvas to [start writing a `README.md` file](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/), or landing page, for your project
- [x] Link to your README in a comment on this issue
- [x] Add an [open license](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/sharing-your-work-in-the-open/) to your repository as a file called `LICENSE.md`
- [x] Add a [Code of Conduct](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-a-code-of-conduct/) to your repository as a file called `CODE_OF_CONDUCT.md`
- [x] Invite new contributors to into your work!

This issue is here to help you keep track of work as you start Open Life Science program. Please refer to the [OLS-1 Syllabus](https://openlifesci.org/ols-1) for more detailed weekly notes and assignments past week 4.

---
# Vision statement
I’m working towards creating a webpage that will have important information on Kenya's open resources (open access, open data, open education, open scholarships). This webpage will also have links to individuals and institutions championing for and/or practicing Open . Furthermore, to improve the interaction between the Open Contributors and Open Users, we will be creating as well a Gitter chatroom. As a long- term strategy, mentorship program will then be initiated for capacity building of open enthusiasts in the Gitter room. As a result, everyone accessing and using these platforms will be able to recreate and download the resources freely while sharing their voices enabling shaping Open policy in the future.

# Why this project? 
Just as any other social movement in the past, Socioeconomic divides and disconnect between advocates and scientists have negatively influenced and continue influencing their progress. We don't want the same to happen to Open movement in Kenya. As a result, while sharing with OLS 2020 mentees, we will create a platform enabling open science and policy advocates and practitioners work together while mentoring each other. More about **Open Connect- Kenya** can be found in the [README file](https://github.com/Lilian9/Open_Connect_Kenya/blob/master/README.md)

# Open Canvas
The Open Canvas allows you to understand the why, who and how of the Open Connect Kenya project implementation journey. [Click here](https://docs.google.com/presentation/d/1NChXWY8HEZ_2LctWk6aufli_Qv8CgTO0t5QbjXTfaSI/edit#slide=id.p)

# Roadmap
https://github.com/Lilian9/Open-Connect-Kenya/issues/3#issue-561202680

**Comment by bebatut** [comment]
@Lilian9 feel free to edit the issue’s checklist above once you are done with a task

**Comment by Fnyasimi** [comment]
This project is quite interesting as we will be incorporating some of the aspects in our project too. We can work together to improving the open policy narrative within our region.

**Comment by Lilian9** [comment]
@Fnyasimi Thanks. this is really great to hear! It will be a learning curve for me with this project and more brains to it will make it easier. What's your project title so that i can read your vision statement?

**Comment by cassgvp** [comment]
Hey @Lilian9 ! You might find these [open research primers](https://www.bristol.ac.uk/psychology/research/ukrn/about/resources/) a useful starting point to create your own specific guides on data sharing etc. 🙂

**Comment by Fnyasimi** [comment]
> @Fnyasimi Thanks. this is really great to hear! It will be a learning curve for me with this project and more brains to it will make it easier. What's your project title so that i can read your vision statement?

Bioinformatics Hub of Kenya #3

**Comment by Lilian9** [comment]
> 
> 
> Hey @Lilian9 ! You might find these [open research primers](https://www.bristol.ac.uk/psychology/research/ukrn/about/resources/) a useful starting point to create your own specific guides on data sharing etc. 🙂
Thanks @cassgvp ! this was really one of my tasks

**Comment by KristinaRiemer** [comment]
Hi @Lilian9, this looks like an awesome project! I'm just curious if you have any ideas about what your platform might be, some sort of website? I imagine there might good templates for a website like this out there, I'll keep a look out.

**Comment by Lilian9** [comment]
Thanks @KristinaRiemer ! I'm thinking of a website too. I didn't know how the platform will look like when I started this project. I just knew i wanted a platform that will bridge the gap within open movement. Therefore, I'm open to any recommendations as I continue learning and working on this!

**Comment by yochannah** [comment]
@Lilian9 @KristinaRiemer - it is also possible to set up a basic website using GitHub - I think we'll cover some of the starting tips for this in the optional GitHub call in a couple of weeks - https://openlifesci.org/ols-1/week05-extra/ 

the @open-life-science website is also hosted on GitHub - https://github.com/open-life-science/open-life-science.github.io

**Comment by Fnyasimi** [comment]
@yochannah and @KristinaRiemer  We also intend to host our website on Github and a few basic set ups, tutorials and layouts will come in handy.

**Comment by Lilian9** [comment]
> 
> 
> @Lilian9 @KristinaRiemer - it is also possible to set up a basic website using GitHub - I think we'll cover some of the starting tips for this in the optional GitHub call in a couple of weeks - https://openlifesci.org/ols-1/week05-extra/
> 
> the @open-life-science website is also hosted on GitHub - https://github.com/open-life-science/open-life-science.github.io

@yochannah awesome! looking forward to learning about this!

**Comment by sudarshangc** [comment]
Awesome! I found similar projects on democratizing the bioinformatics. Would be great to collaborate.

**Comment by Lilian9** [comment]
> 
> 
> Awesome! I found similar projects on democratizing the bioinformatics. Would be great to collaborate.

yes sure! can we link up this week please?

**Comment by yochannah** [comment]
Hi Project Leads,

  This is your project report file: 

https://hackmd.io/a3wx3XuVSjaDaEFblw5b2A?both

Please start working on it for the final presentation. We will send more info in the weekly email.

  Best,  

OLS team
